# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: ArchiveFiles@2
  inputs:
   rootFolderOrFile: '$(Build.SourcesDirectory)'
   includeRootFolder: true
   archiveType: 'zip'
   archiveFile: '$(Build.SourcesDirectory)/vulpy.zip'
   replaceExistingArchive: true

- script: |
       curl -sSO https://tools.veracode.com/integrations/API-Wrappers/C%23/bin/VeracodeC%23API.zip
       ls
  displayName: 'Unzip c# api wrapper'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '**/*API.zip'
    destinationFolder: '$(Build.SourcesDirectory)'
    cleanDestinationFolder: false
    overwriteExistingFiles: false



- task: CmdLine@2
  displayName: 'Veracode cmd line scan'
  inputs:
    script: |
      ls
      echo  '$(System.DefaultWorkingDirectory)'
      echo '$(Build.SourcesDirectory)'
      $(Build.SourcesDirectory)/VeracodeC#API.exe -vid 3d43e6c19ba62a029b4d74ef3274f64e -vkey bcbf7a5c957bb8495ec1be6dbd71a7b6b7549eaed57bd04a81b9d4ec5f61c3c8d634bc68c8139828d0c714bdb1bac088304391e9043f59207801e6cdc062271e -action uploadandscan 
              - f $(Build.SourcesDirectory)/vulpy.zip -appname "vulpy" createprofile true


